---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(stringr)
```


```{r}

#1 - read the data into R
meteorite_data <- read.csv("data/meteorite_landings.csv")
head(meteorite_data, n= 20)
names(meteorite_data)
glimpse(meteorite_data)
```

```{r}
meteorite_rename <- meteorite_data %>% 
  rename(mass_g = mass..g.)
```


```{r}
meteorite_separate <- meteorite_rename %>% 
  separate(GeoLocation, c("latitude", "longitude"), sep = ",") 
coords_update <- meteorite_separate %>% 
  mutate(latitude = str_replace_all(latitude, "\\(", ""),
         longitude = str_replace_all(longitude, "\\)", "")) %>% 
  mutate(latitude = as.numeric(latitude),
       longitude = as.numeric(longitude))
  
coords_update

```


```{r}
#Missing data
coords_update %>%
  summarise(count = sum(is.na(latitude))) #7315
coords_update %>%
  summarise(count = sum(is.na(longitude))) #7315


meteorite_missings <- coords_update %>% 
  mutate(latitude = coalesce(latitude, 0,),
         longitude = coalesce(longitude,0,)
         )
```

```{r}
#Missing data check
meteorite_missings %>%
  summarise(count = sum(is.na(latitude))) #0
meteorite_missings %>%
  summarise(count = sum(is.na(longitude))) #0


```


```{r}
meteorite_gtr_1000g <- meteorite_missings %>% 
filter(mass_g >= 1000)

```

```{r}
meteorite_ordered <- meteorite_gtr_1000g %>% 
  arrange(desc(year))

view(meteorite_ordered)
```


```{r}
write.csv(meteorite_ordered,"C:\\Users\\user\\Documents\\CodeClan\\codeclan_homework_LinziPidgeon\\codeclan_homework_LinziPidgeon\\week_02\\Weekend\\data\\meteorite_ordered.csv")


```

