---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(stringr)

```


```{r}
#1. Read the cleaned data into your environment.
meteorite_cleaned <- read.csv("data/meteorite_ordered.csv")
view(meteorite_cleaned)
glimpse(meteorite_cleaned)
names(meteorite_cleaned)
```


```{r}
#2. Find the names and years found for the 10 largest meteorites in the data.
meteorite_cleaned %>% 
      slice_max(mass_g, n=10) %>% 
select(name, year, mass_g)

```


```{r}
#3. Find the average mass of meteorites that were recorded falling, vs. those which were just found.

meteorite_cleaned %>%
  summarise(count = sum(is.na(fall)))

meteorite_cleaned %>% 
  group_by(fall) %>% 
  summarise(fall_count = n(),(mean(mass_g)))
  
```


```{r}
#4. Find the number of meteorites in each year, for every year since 2000.

meteorite_cleaned %>%
  filter(year >= 2000) %>% 
  group_by(year) %>% 
  summarise(fall_count = n())
```


```{r}
#5. Write a function called `get_meteorite_count()` that takes in two arguments: a dataframe and a year, and returns the phrase "In (input_year), there were (number of meteorites that year) meteorites." IF there are 1 or more meteorites that year. If there are no meteorites in the year, return the phrase "As far as we know, there were no meteorites that year".

get_meteorite_count() <- function(dataframe, year) {
  
  #in here goes lots of code
  
  output_message <- paste("In" year, there were (number of meteorites that year) meteorites.
  
  return(message)
}

get_meteorite_count()


 t <- n * (n + 1) / 2
  return(t)

 adder_G <- function(input1, input2) {
  # here goes lots of code
  output1 <- input1 * 10
  output2 <- input2 * 100
  
  return(c(output1, output2))
}

adder_G(1, 2)
 
 

make_ordered_list <- function(my_list) {
  my_list_sorted <- sort(my_list)
  my_list_joined <- paste(my_list_sorted, collapse = ', ')
  my_message <- paste('Ordered list:', my_list_joined)
  return(my_message)

```

